package com.blog.ljtatum.eekspellingi.enums;

public enum WordCategory {
	CATEGORY_OBJECT, CATEGORY_PLACE, CATEGORY_NUMBER, CATEGORY_COLOR, 
	CATEGORY_PLACE_NUMBER, CATEGORY_COLOR_NUMBER, CATEGORY_ACTION, CATEGORY_ANIMAL,
	CATEGORY_OBJECT_ANIMAL, CATEGORY_DAY_MONTH, CATEGORY_ACTION_ANIMAL,
	CATEGORY_CAREER, CATEGORY_MATH, CATEGORY_SCIENCE, CATEGORY_MATH_SCIENCE,
	CATEGORY_CAREER_SCIENCE
}
