package com.blog.ljtatum.eekspellingi.enums;

public enum WordCategory {
	CATEGORY_OBJECT_PLACE, CATEGORY_OBJECT_NUMBER, CATEGORY_OBJECT_COLOR,
	CATEGORY_PLACE_NUMBER_COLOR, CATEGORY_OBJECT_ACTION, CATEGORY_OBJECT_ANIMAL,
	CATEGORY_OBJECT_DAY_MONTH, CATEGORY_ACTION_ANIMAL_DAY_MONTH
}
